name: Publish Artifacts

on:
  push:
    branches: [ "helm-workflow-fix" ]

jobs:

  # build-and-test:
  #   uses: ./.github/workflows/build-and-test.yaml
  #   with:
  #     PROJECT: helm-release-cleaner
  #   secrets: inherit

  # publish-image:
  #   needs: build-and-test
  #   uses: ./.github/workflows/publish-image.yaml
  #   with:
  #     PROJECT: helm-release-cleaner
  #     DOCKERREGISTRY: abualks
  #   secrets: inherit

  publish-chart:
    # needs: publish-image
    uses: ./.github/workflows/publish-chart.yaml
    with:
      PROJECT: helm-release-cleaner
      OWNER: sarmad-abualkaz
      REPOSITORY: my-helm-charts
      BRANCH: main
    secrets: inherit
